AssetsMVC/Controllers/CPUEntryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Data.Entity.Core.EntityClient;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Configuration;
using System.Web.Mvc;
using ClosedXML;
using ClosedXML.Excel;
using Assets_MVC_.Models;
using AssetsMVC.Models;

namespace AssetsMVC.Controllers
{
    public class CPUEntryController : Controller
    {
        private AssetsDBContext db = new AssetsDBContext();

        // GET: /CPUEntry/
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {


                var CPU = TableCPUEntry().ToList();
                return View(CPU);
            }
            else return RedirectToAction("Login", "Account");
        }

        [HttpPost]
        public ActionResult ExportData()
        {
            GridView gv = new GridView();
            gv.DataSource = TableCPUEntry();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=Consolidated CPU Details.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            gv.RenderControl(htw);
            gv.HeaderRow.Style.Add("width", "15%");
            gv.HeaderRow.Style.Add("font-size", "10px");
            gv.Style.Add("text-decoration", "none");
            gv.Style.Add("font-family", "Arial, Helvetica, sans-serif;");
            gv.Style.Add("font-size", "26px");
            for (int col = 0; col < gv.HeaderRow.Controls.Count; col++)
            {
                TableCell tc = gv.HeaderRow.Cells[col];
                tc.Style.Add("color", "#FFFFFF");
                tc.Style.Add("background-color", "#444");
            }
            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();


            //using (XLWorkbook wb = new XLWorkbook())
            //{
            //    wb.Worksheets.Add();
            //    wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            //    wb.Style.Font.Bold = true;

            //    Response.Clear();
            //    Response.Buffer = true;
            //    Response.Charset = "";
            //    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            //    Response.AddHeader("content-disposition", "attachment;filename= EmployeeReport.xlsx");

            //    using (MemoryStream MyMemoryStream = new MemoryStream())
            //    {
            //        wb.SaveAs(MyMemoryStream);
            //        MyMemoryStream.WriteTo(Response.OutputStream);
            //        Response.Flush();
            //        Response.End();
            //    }
            //}  

            return View(TableCPUEntry().ToList());
        }


        // GET: /CPUEntry/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cpuentry16 cpuentry16 = await db.cpuentry16.FindAsync(id);
            if (cpuentry16 == null)
            {
                return HttpNotFound();
            }
            return View(cpuentry16);
        }

        // GET: /CPUEntry/Create
        public ActionResult Create()
        {
            ddlLoad();
            return View();
        }

        // POST: /CPUEntry/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,asset_id,assetLocation_id,make_id,model_id,productnumber,serialnumber,assetowner,configuration,warranty,warrantyupto,remarks,lastedit,accessory_id,active")] cpuentry16 cpuentry16)
        {
            if (ModelState.IsValid)
            {
                db.cpuentry16.Add(cpuentry16);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ddlLoad();
            return View();
        }

        // GET: /CPUEntry/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cpuentry16 cpuentry16 = await db.cpuentry16.FindAsync(id);
            if (cpuentry16 == null)
            {
                return HttpNotFound();
            }
            ddlLoad();
            return View(cpuentry16);
        }

        // POST: /CPUEntry/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,asset_id,assetLocation_id,make_id,model_id,productnumber,serialnumber,assetowner,configuration,warranty,warrantyupto,remarks,lastedit,accessory_id,active")] cpuentry16 cpuentry16)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cpuentry16).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cpuentry16);
        }

        // GET: /CPUEntry/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cpuentry16 cpuentry16 = await db.cpuentry16.FindAsync(id);
            if (cpuentry16 == null)
            {
                return HttpNotFound();
            }
            return View(cpuentry16);
        }

        // POST: /CPUEntry/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            cpuentry16 cpuentry16 = await db.cpuentry16.FindAsync(id);
            db.cpuentry16.Remove(cpuentry16);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public ActionResult Import()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Import(cpuEntyImport imp)
        {
            int count = 0;
            if (imp.getData!= null)
            {
                var table = imp.getData;
                if (table != null)
                {
                    string[] rows = table.Split('\n');
                    string[] cells;
                    for (int i = 0; i <= rows.Length - 1; i++)
                    {
                        cells = rows[i].Split('\t');
                        if (cells.Count() == 13)
                        {
                            bool Inset = ValidateandInsert(cells);
                            if (Inset)
                            {
                                count++;
                            }
                        }
                        //if (!Inset) break;
                    }
                }
            }
            ViewBag.Message = "No of Entry Placed is: " + count;
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #region SupportingFunctions
        #region ddlLoad

        public void ddlLoad()
        {
            var m = db.mas_make.Where(i => i.accessoryId == 1).Select(i => new { i.id, i.make });
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (var l in m)
            {
                list.Add(new SelectListItem
                {
                    Text = l.make,
                    Value = l.id.ToString()
                });
            }
            ViewData["Make"] = new SelectList(list, "Value", "Text", "");


            List<SelectListItem> model = new List<SelectListItem>();
            var a = db.mas_model.Where(i => i.accessoryId == 1).Select(i => new { i.id, i.model });
            foreach (var l in a)
            {
                model.Add(new SelectListItem
                {
                    Text = l.model,
                    Value = l.id.ToString()
                });
            }
            ViewData["model"] = new SelectList(model, "Value", "Text", "");

            List<SelectListItem> classification = new List<SelectListItem>();
            var c = db.mas_classification.Select(i => new { i.id, i.classification });
            foreach (var l in c)
            {
                classification.Add(new SelectListItem
                {
                    Text = l.classification,
                    Value = l.id.ToString()
                });
            }
            ViewData["classification"] = new SelectList(classification, "Value", "Text", "");

            List<SelectListItem> owner = new List<SelectListItem>();
            var o = db.mas_owner.Select(i => new { i.id, i.owner });
            foreach (var l in o)
            {
                owner.Add(new SelectListItem
                {
                    Text = l.owner,
                    Value = l.id.ToString()
                });
            }
            ViewData["owner"] = new SelectList(owner, "Value", "Text", "");

            List<SelectListItem> warranty = new List<SelectListItem>();

AssetsMVC/Views/CPUEntry/Create.cshtml
@model Assets_MVC_.Models.cpuentry16

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>
<small>New CPU Entry</small>
@section style{
<link href="~/CustomStyleSheets/style.css" rel="stylesheet" />
@Styles.Render("~/Content/themes/base/jquery-ui.css")
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.asset_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.asset_id)
                @Html.ValidationMessageFor(model => model.asset_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assetLocation_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assetLocation_id)
                @Html.ValidationMessageFor(model => model.assetLocation_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.make_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.make_id, new SelectList((System.Collections.IEnumerable)ViewData["Make"], "Value", "Text"), "--- Select Make---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.make_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.model_id, new SelectList((System.Collections.IEnumerable)ViewData["model"], "Value", "Text"), "--- Select Model---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.model_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productnumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productnumber)
                @Html.ValidationMessageFor(model => model.productnumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.serialnumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serialnumber)
                @Html.ValidationMessageFor(model => model.serialnumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.configuration, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.configuration)
                @Html.ValidationMessageFor(model => model.configuration)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assetowner, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.assetowner, new SelectList((System.Collections.IEnumerable)ViewData["owner"], "Value", "Text"), "--- Select Owner---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.assetowner)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.classification_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.classification_id, new SelectList((System.Collections.IEnumerable)ViewData["classification"], "Value", "Text"), "--- Select Classification---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.classification_id)
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.warranty, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.warranty, new SelectList((System.Collections.IEnumerable)ViewData["warranty1"], "Value", "Text"), "--- Select warranty---", new { @class = "chosen-select" })
                @*@Html.EditorFor(model => model.warranty)*@
                @Html.ValidationMessageFor(model => model.warranty)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.warrantyupto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.warrantyupto)
                @Html.ValidationMessageFor(model => model.warrantyupto)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remarks, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remarks)
                @Html.ValidationMessageFor(model => model.remarks)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.active, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.active, new SelectList((System.Collections.IEnumerable)ViewData["active1"], "Value", "Text"), "--- Select Active---", new { @class = "chosen-select" }) 
                @Html.ValidationMessageFor(model => model.active)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")

<script type="text/javascript">
    $(document).ready(function () {
        $(".chosen-select").chosen({ no_results_text: "Oops, nothing found!" });
                $("#make_id").on("change", function () {

                    $.ajax(
                    {
                        url: '@Url.Action("GetModel", "CPUEntry")',
                        type: 'POST',
                        data: "{'make':'" + $(this).val() + "'}",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {

                            var markup = "<option value='0'>--- Select Model ---</option>";
                            for (var x = 0; x < data.length; x++) {
                                markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                            }
                            $("#model_id").html(markup);
                            $("#model_id").trigger('chosen:updated');
                        },
                        error: function (response) {
                            alert("error");
                            alert(response.responseText);
                        },
                        failure: function () {
                            alert("failed");
                        }
                    });
                });


                $("#model_id").on("change", function () {

                    $.ajax(
                    {
                        url: '@Url.Action("GetConfiguration", "CPUEntry")',
                        type: 'POST',
                        data: "{'id':'" + $(this).val() + "'}",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            alert(data);
                            $("#configuration").val(data);
                        },
                        error: function (response) {
                            alert("error");
                            alert(response.responseText);
                        },
                        failure: function () {
                            alert("failed");
                        }
                    });
                });


            $("#ddlUser").on("change", function () {
                //alert($(this).val());
                //alert($("#ddlProject").val())
                $.ajax(
                {
                    url: '@Url.Action("GetRoles", "Role")',
                    type: 'POST',
                    data: "{'UserId':'" + $(this).attr("value")+ "', '_project':'" + $('#ddlProject').attr("value") +"'}",
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        var markup = "<option value='0'>--- Select Role ---</option>";
                        for (var x = 0; x < data.length; x++) {
                            markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                        }
                        $("#ddlRole").html(markup).show();
                    },
                    error: function (response) {
                        alert("error");
                        alert(response.responseText)
                    },
                    failure: function () {
                        alert("failed");
                    }
                });
            });
            })
</script>

}

AssetsMVC/Views/CPUEntry/Edit.cshtml
@model Assets_MVC_.Models.cpuentry16

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section style{
<link href="~/CustomStyleSheets/style.css" rel="stylesheet" />
}
<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="color:magenta;">CPU @Model.asset_id (@Model.assetLocation_id)</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.asset_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.asset_id)
                @Html.ValidationMessageFor(model => model.asset_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assetLocation_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assetLocation_id)
                @Html.ValidationMessageFor(model => model.assetLocation_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.make_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.make_id, new SelectList((System.Collections.IEnumerable)ViewData["Make"], "Value", "Text"), "--- Select Make---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.make_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.model_id, new SelectList((System.Collections.IEnumerable)ViewData["model"], "Value", "Text"), "--- Select Make---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.model_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productnumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productnumber)
                @Html.ValidationMessageFor(model => model.productnumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.serialnumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serialnumber)
                @Html.ValidationMessageFor(model => model.serialnumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assetowner, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.assetowner, new SelectList((System.Collections.IEnumerable)ViewData["owner"], "Value", "Text"), "--- Select Owner---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.assetowner)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.classification_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.classification_id, new SelectList((System.Collections.IEnumerable)ViewData["classification"], "Value", "Text"), "--- Select Classification---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.classification_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.configuration, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.configuration)
                @Html.ValidationMessageFor(model => model.configuration)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.warranty, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.warranty, new SelectList((System.Collections.IEnumerable)ViewData["warranty1"], "Value", "Text"), "--- Select warranty---", new { @class = "chosen-select" })
                @*@Html.EditorFor(model => model.warranty)*@
                @Html.ValidationMessageFor(model => model.warranty)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.warrantyupto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.warrantyupto )
                @Html.ValidationMessageFor(model => model.warrantyupto)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remarks, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remarks)
                @Html.ValidationMessageFor(model => model.remarks)
            </div>
        </div>


       
        <div class="form-group">
            @Html.LabelFor(model => model.active, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.active, new SelectList((System.Collections.IEnumerable)ViewData["active1"], "Value", "Text"), "--- Select Active---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.active)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/jquery.ui.datepicker.css")
    @Styles.Render("~/Content/themes/base/jquery.ui.autocomplete.css")
    @Styles.Render("~/Content/themes/base/jquery-ui.css")

    <script type="text/javascript">
        $(document).ready(function () {
            $(".chosen-select").chosen({ no_results_text: "Oops, nothing found!" });
                $("#make_id").on("change", function () {

                    $.ajax(
                    {
                        url: '@Url.Action("GetModel", "CPUEntry")',
                        type: 'POST',
                        data: "{'make':'" + $(this).val() + "'}",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            alert("Success");
                            var markup = "<option value='0'>--- Select Model ---</option>";
                            for (var x = 0; x < data.length; x++) {
                                markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                            }
                            $("#model_id").html(markup);
                            $("#model_id").trigger('chosen:updated');
                        },
                        error: function (response) {
                            alert("error");
                            alert(response.responseText);
                        },
                        failure: function () {
                            alert("failed");
                        }
                    });
                });


                $("#model_id").on("change", function () {

                    $.ajax(
                    {
                        url: '@Url.Action("GetConfiguration", "CPUEntry")',
                        type: 'POST',
                        data: "{'id':'" + $(this).val() + "'}",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            alert(data);
                            $("#configuration").val(data);
                        },
                        error: function (response) {
                            alert("error");
                            alert(response.responseText);
                        },
                        failure: function () {
                            alert("failed");
                        }
                    });
                });


            $("#ddlUser").on("change", function () {
                //alert($(this).val());
                //alert($("#ddlProject").val())
                $.ajax(
                {
                    url: '@Url.Action("GetRoles", "Role")',
                    type: 'POST',
                    data: "{'UserId':'" + $(this).attr("value")+ "', '_project':'" + $('#ddlProject').attr("value") +"'}",
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        var markup = "<option value='0'>--- Select Role ---</option>";
                        for (var x = 0; x < data.length; x++) {
                            markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                        }
                        $("#ddlRole").html(markup).show();
                    },
                    error: function (response) {
                        alert("error");
                        alert(response.responseText)
                    },
                    failure: function () {
                        alert("failed");
                    }
                });
            });
            })
    </script>

}