AssetsMVC/Controllers/MouseController.cs
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Net;
    using System.Web;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.IO;
    using System.Configuration;
    using System.Web.Mvc;
    using ClosedXML;
    using ClosedXML.Excel;
    using Assets_MVC_.Models;
    using AssetsMVC.Models;

namespace AssetsMVC.Controllers
{
    public class MouseController : Controller
    {
        private AssetsDBContext db = new AssetsDBContext();

        // GET: /Mouse/
        public ActionResult Index()
        {
            var Mouse = TableMouseEntry();
            return View(Mouse);
        }
        public ActionResult Import()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Import(EntyImport imp)
        {
            var table = imp.getData;

            if (table != null)
            {
            string[] rows = table.Split('\n');
            string[] cells; int count=0;
             
            for (int i = 0; i <= rows.Length - 1; i++)
            {
                cells = rows[i].Split('\t');
                if (cells.Count() == 12)
                {
                    bool Inset = ValidateandInsert(cells);
                    if(Inset)
                    {
                        count++;
                    }
                }
                //if (!Inset) break;
            }
            ViewBag.Message = "No of Entry Placed is: " + count;
            return View();
            }
            return RedirectToAction("Import");
        }
        // GET: /Mouse/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //mouseentry16 mouseentry16 = await db.mouseentry16.FindAsync(id);
            var mouse =  TableMouseEntry();
            if (mouse == null)
            {
                return HttpNotFound();
            }
            return View(mouse);
        }

        // GET: /Mouse/Create
        public ActionResult Create()
        {
            ddlLoad();
            return View();
        }

        // POST: /Mouse/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="id,asset_id,assetLocation_id,make_id,model_id,productnumber,serialnumber,assetowner,Type,classification_id,warranty,warrantyupto,remarks,lastedit,active")] mouseentry16 mouseentry16)
        {
            if (ModelState.IsValid)
            {
                db.mouseentry16.Add(mouseentry16);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(mouseentry16);
        }

        // GET: /Mouse/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mouseentry16 mouseentry16 = await db.mouseentry16.FindAsync(id);
            if (mouseentry16 == null)
            {
                return HttpNotFound();
            }
            ddlLoad();
            return View(mouseentry16);
        }

        // POST: /Mouse/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="id,asset_id,assetLocation_id,make_id,model_id,productnumber,serialnumber,assetowner,Type,classification_id,warranty,warrantyupto,remarks,lastedit,active")] mouseentry16 mouseentry16)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mouseentry16).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(mouseentry16);
        }

        // GET: /Mouse/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mouseentry16 mouseentry16 = await db.mouseentry16.FindAsync(id);
            if (mouseentry16 == null)
            {
                return HttpNotFound();
            }
            var mouse = TableMouseEntry();
            return View(mouse);
        }

        // POST: /Mouse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            mouseentry16 mouseentry16 = await db.mouseentry16.FindAsync(id);
            db.mouseentry16.Remove(mouseentry16);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region ddlLoad

        public void ddlLoad()
        {
            var m = db.mas_make.Where(i => i.accessoryId == db.mas_Accessory.Where(a => a.accessory == "MOUSE").Select(a => a.id).FirstOrDefault()).Select(i => new { i.id, i.make });
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (var l in m)
            {
                list.Add(new SelectListItem
                {
                    Text = l.make,
                    Value = l.id.ToString()
                });
            }
            ViewData["Make"] = new SelectList(list, "Value", "Text", "");


            List<SelectListItem> model = new List<SelectListItem>();
            var mod = db.mas_model.Where(i => i.accessoryId == db.mas_Accessory.Where(a => a.accessory == "MOUSE").Select(a => a.id).FirstOrDefault()).Select(i => new { i.id, i.model });
            foreach (var l in mod)
            {
                model.Add(new SelectListItem
                {
                    Text = l.model,
                    Value = l.id.ToString()
                });
            }
            ViewData["model"] = new SelectList(model, "Value", "Text", "");

            List<SelectListItem> classification = new List<SelectListItem>();
            var c = db.mas_classification.Select(i => new { i.id, i.classification });
            foreach (var l in c)
            {
                classification.Add(new SelectListItem
                {
                    Text = l.classification,
                    Value = l.id.ToString()
                });
            }
            ViewData["classification"] = new SelectList(classification, "Value", "Text", "");

            List<SelectListItem> owner = new List<SelectListItem>();
            var o = db.mas_owner.Select(i => new { i.id, i.owner });
            foreach (var l in o)
            {
                owner.Add(new SelectListItem
                {
                    Text = l.owner,
                    Value = l.id.ToString()
                });
            }
            ViewData["owner"] = new SelectList(owner, "Value", "Text", "");

            List<SelectListItem> warranty = new List<SelectListItem>();

            warranty.Add(new SelectListItem
            {
                Text = "Yes",
                Value = "True"
            });
            warranty.Add(new SelectListItem
            {
                Text = "No",
                Value = "False"
            });

            ViewData["warranty1"] = new SelectList(warranty, "Value", "Text", "");

            List<SelectListItem> active = new List<SelectListItem>();

            active.Add(new SelectListItem
            {
                Text = "Yes",
                Value = "True"
            });
            active.Add(new SelectListItem
            {
                Text = "No",
                Value = "False"
            });

            ViewData["active1"] = new SelectList(active, "Value", "Text", "");

            List<SelectListItem> type = new List<SelectListItem>();

            type.Add(new SelectListItem
            {
                Text = "Ps/2",
                Value = "Ps/2"
            });
            type.Add(new SelectListItem
            {
                Text = "PS2",
                Value = "PS2"
            });
            type.Add(new SelectListItem
            {
                Text = "USB",
                Value = "USB"
            });
            type.Add(new SelectListItem
            {
                Text = "WIRELESS",
                Value = "WIRELESS"
            });


            ViewData["type1"] = new SelectList(type, "Value", "Text", "");

        }
        #endregion

        #region Supporting Function
        public bool ValidateandInsert(string[] cells)
        {
            mouseentry16 monitor = new mouseentry16();
            int makeId;
            bool flag = false;
            bool asset_Id = CheckDuplicate("mouseentry16", "asset_id", "S", cells[2].Trim());
            if (asset_Id)
            {

                return false;
            }
            else
            {
                monitor.asset_id = cells[2].Trim();
                flag = true;
            }
            bool assetLocation = CheckDuplicate("mas_assetlocation", "assetLocation", "S", cells[1].Trim());
            if (assetLocation)
            {
                monitor.assetLocation_id = cells[1].Trim();
                flag = true;

AssetsMVC/Views/Mouse/Create.cshtml
@model Assets_MVC_.Models.mouseentry16

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section style{
<link href="~/CustomStyleSheets/style.css" rel="stylesheet" />
}

<h1>Create</h1>
<small>New Mouse Entry</small>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.asset_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.asset_id)
                @Html.ValidationMessageFor(model => model.asset_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assetLocation_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assetLocation_id)
                @Html.ValidationMessageFor(model => model.assetLocation_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.make_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.make_id, new SelectList((System.Collections.IEnumerable)ViewData["Make"], "Value", "Text"), "Choose Mouse Make", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.make_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.model_id, new SelectList((System.Collections.IEnumerable)ViewData["model"], "Value", "Text"), "Choose Mouse Model", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.model_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productnumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productnumber)
                @Html.ValidationMessageFor(model => model.productnumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.serialnumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serialnumber)
                @Html.ValidationMessageFor(model => model.serialnumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assetowner, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.assetowner, new SelectList((System.Collections.IEnumerable)ViewData["owner"], "Value", "Text"), "Choose Owner", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.assetowner)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, new SelectList((System.Collections.IEnumerable)ViewData["type1"], "Value", "Text"), "Choose Type", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.classification_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.classification_id, new SelectList((System.Collections.IEnumerable)ViewData["classification"], "Value", "Text"), "Choose Classification", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.classification_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.warranty, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.warranty, new SelectList((System.Collections.IEnumerable)ViewData["warranty1"], "Value", "Text"), "Choose warranty", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.warranty)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.warrantyupto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.warrantyupto)
                @Html.ValidationMessageFor(model => model.warrantyupto)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remarks, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remarks)
                @Html.ValidationMessageFor(model => model.remarks)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.active, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.active, new SelectList((System.Collections.IEnumerable)ViewData["active1"], "Value", "Text"), "Choose Active", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.active)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
      
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/jquery-ui.css")

    <script type="text/javascript">
    
        $(document).ready(function () {
            $(".chosen-select").chosen({ no_results_text: "Oops, nothing found!" });
                $("#make_id").on("change", function () {

                    $.ajax(
                    {
                        url: '@Url.Action("GetModel", "Mouse")',
                        type: 'POST',
                        data: "{'make':'" + $(this).val() + "'}",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            var markup = "<option value='0'>Choose Mouse Model</option>";
                            var li_markup = '<li class="active-result" data-option-array-index=0>--- Select Model ----</li>';
                            for (var x = 0; x < data.length; x++) {
                                markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                                li_markup += '<li class="active-result" data-option-array-index=' + x+1 + '>' + data[x].Text + '</li>';
                            }
                   
                            $("#model_id").html(markup);
                            $("#model_id").trigger('chosen:updated');
                        },
                        error: function (response) {
                            alert("error");
                            alert(response.responseText);
                        },
                        failure: function () {
                            alert("failed");
                        }
                    });
                });


                @*$("#model_id").on("change", function () {

                    $.ajax(
                    {
                        url: '@Url.Action("GetConfiguration", "Mouse")',
                        type: 'POST',
                        data: "{'id':'" + $(this).val() + "'}",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                          $("#configuration").val(data);
                        },
                        error: function (response) {
                            alert("error");
                            alert(response.responseText);
                        },
                        failure: function () {
                            alert("failed");
                        }
                    });
                });*@

            });
    </script>

}

AssetsMVC/Views/Mouse/Delete.cshtml
@model Assets_MVC_.Models.mouseentry16

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete <small style="color:magenta;">Mouse @Model.asset_id (@Model.assetLocation_id)</small></h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>mouseentry16</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.asset_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.asset_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.assetLocation_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.assetLocation_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.make_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.make_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.model_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.model_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productnumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productnumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.serialnumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.serialnumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.assetowner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.assetowner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.classification_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.classification_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.warranty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.warranty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.warrantyupto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.warrantyupto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.remarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastedit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastedit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AssetsMVC/Views/Mouse/Edit.cshtml
@model Assets_MVC_.Models.mouseentry16

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section style{
<link href="~/CustomStyleSheets/style.css" rel="stylesheet" />
}
<h1>Edit</h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="color:magenta;">Mouse @Model.asset_id (@Model.assetLocation_id)</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.asset_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.asset_id)
                @Html.ValidationMessageFor(model => model.asset_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assetLocation_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assetLocation_id)
                @Html.ValidationMessageFor(model => model.assetLocation_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.make_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.make_id, new SelectList((System.Collections.IEnumerable)ViewData["Make"], "Value", "Text"), "--- Select Make---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.make_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.model_id, new SelectList((System.Collections.IEnumerable)ViewData["model"], "Value", "Text"), "--- Select Model---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.model_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productnumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productnumber)
                @Html.ValidationMessageFor(model => model.productnumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.serialnumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serialnumber)
                @Html.ValidationMessageFor(model => model.serialnumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assetowner, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.assetowner, new SelectList((System.Collections.IEnumerable)ViewData["owner"], "Value", "Text"), "--- Select Owner---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.assetowner)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, new SelectList((System.Collections.IEnumerable)ViewData["type1"], "Value", "Text"), "--- Select Type---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.classification_id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.classification_id, new SelectList((System.Collections.IEnumerable)ViewData["classification"], "Value", "Text"), "--- Select Classification---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.classification_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.warranty, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.warranty, new SelectList((System.Collections.IEnumerable)ViewData["warranty1"], "Value", "Text"), "--- Select warranty---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.warranty)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.warrantyupto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.warrantyupto)
                @Html.ValidationMessageFor(model => model.warrantyupto)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remarks, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remarks)
                @Html.ValidationMessageFor(model => model.remarks)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.active, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.active, new SelectList((System.Collections.IEnumerable)ViewData["active1"], "Value", "Text"), "--- Select Active---", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.active)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/jquery-ui.css")

    <script type="text/javascript">
        $(document).ready(function () {
            $(".chosen-select").chosen({ no_results_text: "Oops, nothing found!" });
                $("#make_id").on("change", function () {
                    $.ajax(
                    {
                        url: '@Url.Action("GetModel", "Mouse")',
                        type: 'POST',
                        data: "{'make':'" + $(this).val() + "'}",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            alert("Success");
                            var markup = "<option value='0'>--- Select Model ---</option>";
                            for (var x = 0; x < data.length; x++) {
                                markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                            }
                            $("#model_id").html(markup);
                            $("#model_id").trigger('chosen:updated');
                        },
                        error: function (response) {
                            alert("error");
                            alert(response.responseText);
                        },
                        failure: function () {
                            alert("failed");
                        }
                    });
                });


                $("#model_id").on("change", function () {

                    $.ajax(
                    {
                        url: '@Url.Action("GetConfiguration", "Mouse")',
                        type: 'POST',
                        data: "{'id':'" + $(this).val() + "'}",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            alert(data);
                            $("#configuration").val(data);
                        },
                        error: function (response) {
                            alert("error");
                            alert(response.responseText);
                        },
                        failure: function () {
                            alert("failed");
                        }
                    });
                });

            });
    </script>

}